Repository sovware/directorist, pull requests merged in 2021-11, with the labels that each got.

#475 Add/whatsapp option
  includes/class-helper.php
  includes/model/Listings.php
  includes/model/SingleListing.php
  includes/modules/multi-directory-setup/class-multi-directory-manager.php
  templates/archive/fields/phone.php
  templates/archive/fields/phone2.php
  templates/single/fields/phone.php
  templates/single/fields/phone2.php
Labels: Feature, v7.0.6

#536 File upload issue
  assets/js/global-directorist-plupload.js
  assets/src/js/global/directorist-plupload.js
Labels: v7.0.6

#537 Reset Button functionality fix
  assets/js/public-search-listing.js
  assets/src/js/public/search-listing.js
  views/widgets/search.php
Labels: v7.0.6, theme dep.

#533 Email sending issue on fresh database
  includes/classes/class-email.php
Labels: v7.0.6

#544 Fixed: all listing page dropdown toggle issue
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/public-main.js
  assets/js/public-search-listing.js
  assets/src/js/public/components/atbdDropdown.js
  assets/src/scss/component/_general.scss
Labels: v7.0.6.1
