Repository sovware/directorist, pull requests merged in 2021-10, with the labels that each got.

#478 Remove/plan dependency
  includes/classes/class-metabox.php
Labels: theme dep.

#479 fixed template path issue for extension
  includes/template-functions.php
Labels: theme dep.

#490 fixed logical operator check
  assets/js/global-main.js
  assets/src/js/global/components/select2-custom-control.js
Labels: theme dep.

#474 add template support in ajax search form
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/global-add-listing-gmap-custom-script.js
  assets/js/global-add-listing-openstreet-map-custom-script.js
  assets/js/global-add-listing.js
  assets/js/global-directorist-plupload.js
  assets/js/global-load-osm-map.js
  assets/js/global-main.js
  assets/js/global-map-view.js
  assets/js/public-search-form-listing.js
  assets/js/public-search-listing.js
  assets/src/js/global/add-listing.js
  assets/src/js/lib/helper.js
  assets/src/js/public/components/atbdDropdown.js
  assets/src/js/public/components/general.js
  assets/src/js/public/search-form-listing.js
  assets/src/js/public/search-listing.js
  assets/src/scss/component/_add-listing.scss
  assets/src/scss/component/_advanced-search.scss
  assets/src/scss/component/_alert.scss
  assets/src/scss/component/payment/_checkout-receipt.scss
  assets/src/scss/layout/admin/admin-style.scss
  assets/src/scss/layout/public/search-home.scss
  assets/vendor-js/ez-media-uploader.js
  assets/vendor-js/range-slider.js
  assets/vendor-js/range-slider.rtl.js
  includes/classes/class-ajax-handler.php
  includes/gateways/class-gateway.php
  includes/helper-functions.php
  includes/model/ListingDashboard.php
  templates/listing-form/fields/excerpt.php
  templates/listing-form/submit.php
  templates/search-form-contents.php
  templates/search-form/buttons.php
  templates/search-form/custom-fields/url.php
  templates/search-form/fields/category.php
  templates/search-form/fields/location.php
  templates/search-form/fields/radius_search.php
  templates/search-form/fields/review.php
Labels: v7.0.6, theme dep.

#500 Fixed: Location, Address filed js conflict (#499)
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/global-add-listing-openstreet-map-custom-script.js
  assets/js/global-geolocation.js
  assets/js/public-search-form-listing.js
  assets/js/public-search-listing.js
  assets/src/js/global/map-scripts/add-listing/openstreet-map.js
  assets/src/js/global/map-scripts/geolocation.js
  assets/src/js/public/search-form-listing.js
  assets/src/scss/base/_general.scss
  assets/src/scss/layout/public/search-home.scss
  templates/listing-form/fields/address.php
  templates/search-form/fields/location.php
Labels: theme dep.

#505 System info issue ( Templates )
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/src/scss/layout/admin/admin-style.scss
  includes/system-status/class-system-status.php
  includes/system-status/system-info-template.php
  includes/system-status/system-information/system-information-template.php
  includes/system-status/system-information/system-information.php
  includes/system-status/template.php
Labels: Need rugent review

#523 add new hook
  includes/model/Listings.php
Labels: v7.0.6, theme dep.

#529 My profile improvement
  templates/dashboard/tab-profile.php
Labels: v7.0.6

#527 New design improvements
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/public-search-listing.js
  assets/other/style.php
  assets/src/scss/component/_add-listing.scss
  assets/src/scss/component/_author-profile.scss
  assets/src/scss/component/_widget.scss
  assets/src/scss/component/listing-details/_details-content.scss
  assets/src/scss/component/listing-details/_general.scss
  assets/src/scss/component/listings/_listing-card.scss
  assets/src/scss/component/listings/_listing-category.scss
Labels: v7.0.6
