Repository sovware/directorist, pull requests merged in 2022-11, with the labels that each got.

#1246 Moved deprecated functions in a central place
  directorist-base.php
  includes/deprecated/class-script-helper.php
  includes/deprecated/functions.php
  includes/helper-functions.php
  includes/template-functions.php
Labels: Type: Refactoring

#1239 fix an issue with wrong operator getting assigned if there is multipl…
  includes/model/Listings.php
Labels: Priority: High

#1249 Two more items added in PR template
  .github/pull_request_template.md
Labels: Type: Improvement

#1251 fixed author pagination active nav issue
  assets/js/admin-main.js
  assets/js/all-authors.js
  assets/src/js/public/components/author.js
Labels: Type: Bugfix

#1248 Few queries optimized
  directorist-base.php
  includes/classes/class-listing-db.php
  includes/classes/class-user.php
  includes/data-store/class-atbdp-listing-store.php
  includes/database/db.php
  includes/deprecated/class-atbdp-listing-store.php
  includes/deprecated/class-script-helper.php
  includes/deprecated/functions.php
  includes/helper-functions.php
  includes/model/ListingAuthor.php
  includes/model/ListingDashboard.php
  includes/model/ListingForm.php
  includes/model/ListingTaxonomy.php
  includes/model/Listings.php
  includes/model/SingleListing.php
Labels: Type: Improvement, Priority: High
