Repository sovware/directorist, pull requests merged in 2022-07, with the labels that each got.

#1041 RTL support added
  assets/css/admin-main.rtl.min.css
  assets/css/all-listings.css
  assets/css/all-listings.min.css
  assets/css/all-listings.min.rtl.css
  assets/css/all-listings.rtl.css
  assets/css/all-listings.rtl.min.css
  assets/css/public-main.css
  assets/css/public-main.min.css
  assets/css/public-main.min.rtl.css
  assets/css/public-main.rtl.css
  assets/css/public-main.rtl.min.css
  assets/js/admin-builder-archive.min.js
  assets/js/admin-multi-directory-builder.js
  assets/js/admin-multi-directory-builder.min.js
  assets/js/admin-settings-manager.js
  assets/js/admin-settings-manager.min.js
  assets/js/single-listing.js
  assets/js/single-listing.min.js
  assets/src/js/public/components/single-listing-page/slider.js
  assets/src/scss/component/_range-slider.scss
  assets/src/scss/component/listings/_listing-map.scss
  assets/vendor-css/ez-media-uploader.rtl.min.css
  assets/vendor-js/range-slider.rtl.js
  assets/vendor-js/range-slider.rtl.min.js
  includes/asset-loader/helper.php
  includes/asset-loader/scripts.php
  languages/directorist.pot
  webpack.prod.js
Labels: Coding, Bugfix

#1040 fix typo
  includes/classes/class-setup-wizard.php
  views/admin-templates/import-export/body-templates/step-two.php
Labels: Coding, Bugfix

#1049 Fixed single listing widget map loading issue
  assets/js/openstreet-map.js
  assets/js/single-listing-openstreet-map.js
  assets/src/js/global/map-scripts/single-listing/openstreet-map.js
Labels: Widgets, Bugfix, v7.3.0

#1050 added missing deprecated method
  directorist-base.php
Labels: Coding, Bugfix

#1052 multi directory type responsive style fix
  assets/css/all-listings.css
  assets/css/all-listings.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/admin-main.js
  assets/src/scss/component/_archive.scss
  assets/src/scss/layout/public/search-home.scss
Labels: Bugfix

#1055 Fix related slider loading issue
  assets/js/single-listing.js
  assets/src/js/public/components/single-listing-page/slider.js
Labels: Single Listing, Bugfix

#999 select2 search field issue fixed
  assets/js/search-form.js
  assets/src/js/public/search-form.js
Labels: Search Form, Bugfix

#1016 fixed openstreetmap console error
  assets/vendor-js/openstreet-map/subGroup-markercluster-controlLayers-realworld.388.js
Labels: All Listings, Bugfix

#1064 Unicons now loading internally
  assets/fonts/line/unicons-line.ttf
  assets/fonts/line/unicons-solid.ttf
  assets/unicons-3.0.3/css/line.css
  assets/unicons-3.0.3/css/line.min.css
  assets/unicons-3.0.3/fonts/line/unicons-0.woff2
  assets/unicons-3.0.3/fonts/line/unicons-1.woff2
  assets/unicons-3.0.3/fonts/line/unicons-10.woff2
  assets/unicons-3.0.3/fonts/line/unicons-11.woff2
  assets/unicons-3.0.3/fonts/line/unicons-12.woff2
  assets/unicons-3.0.3/fonts/line/unicons-13.woff2
  assets/unicons-3.0.3/fonts/line/unicons-14.woff2
  assets/unicons-3.0.3/fonts/line/unicons-15.woff2
  assets/unicons-3.0.3/fonts/line/unicons-16.woff2
  assets/unicons-3.0.3/fonts/line/unicons-17.woff2
  assets/unicons-3.0.3/fonts/line/unicons-18.woff2
  assets/unicons-3.0.3/fonts/line/unicons-19.woff2
  assets/unicons-3.0.3/fonts/line/unicons-3.woff2
  assets/unicons-3.0.3/fonts/line/unicons-4.woff2
  assets/unicons-3.0.3/fonts/line/unicons-5.woff2
  assets/unicons-3.0.3/fonts/line/unicons-6.woff2
  assets/unicons-3.0.3/fonts/line/unicons-7.woff2
  assets/unicons-3.0.3/fonts/line/unicons-8.woff2
  assets/unicons-3.0.3/fonts/line/unicons-9.woff2
  includes/asset-loader/scripts.php
Labels: Coding, Security

#1054 completed 'includes/classes/class-user.php'
  assets/js/admin-builder-archive.js
  assets/js/admin-import-export.js
  assets/js/admin-main.js
  assets/src/js/admin/import-export.js
  directorist-base.php
  includes/classes/class-tools.php
  includes/classes/class-upgrade.php
  includes/classes/class-user.php
  views/admin-templates/import-export/body-templates/step-two.php
Labels: Coding, Security

#1068 Security fix 2
  includes/model/Listings.php
  includes/model/SearchForm.php
Labels: Security
