Repository sovware/directorist, pull requests merged in 2023-08, with the labels that each got.

#1543 Query performance optimization
  directorist-base.php
  includes/backward-compatibility.php
  includes/classes/class-add-listing.php
  includes/classes/class-cron.php
  includes/classes/class-custom-post.php
  includes/classes/class-installation.php
  includes/classes/class-metabox.php
  includes/classes/class-setup-wizard.php
  includes/classes/class-tools.php
  includes/custom-filters.php
  includes/helper-functions.php
  includes/model/ListingAuthor.php
  includes/model/ListingDashboard.php
  includes/model/ListingForm.php
  includes/model/Listings.php
  includes/model/SearchForm.php
  includes/model/SingleListing.php
  includes/rest-api/Version1/class-listings-controller.php
  includes/template-functions.php
  includes/update-functions.php
  templates/archive/fields/listings_location.php
Labels: Type: Improvement, Priority: High

#1529 fix issue with pricing plan and featured listing checkbox
  includes/classes/class-metabox.php
Labels: Type: Bug

#1548 Fix/listing import issue
  includes/classes/class-tools.php
  includes/helper-functions.php
  views/admin-templates/import-export/data-table.php
Labels: Type: Bug

#1549 fix email header issue on contact listing owner
  includes/classes/class-ajax-handler.php
Labels: Type: Bug

#1232 Custom files can't be deleted in edit listing
  includes/classes/class-ajax-handler.php
  includes/model/ListingForm.php
Labels: Type: Bug

#1448 Sanitized settings json data for invalid UTF-8 characters
  includes/classes/class-settings-panel.php
Labels: Type: Bug

#1541 fixed instant search conflicting issue
  assets/js/all-listings.js
  assets/src/js/public/components/instantSearch.js
Labels: Type: Bug

#1556 fixed instant search coflicting issue and refactoring
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/all-listings.css
  assets/css/all-listings.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/account.js
  assets/js/add-listing-google-map.js
  assets/js/add-listing-openstreet-map.js
  assets/js/add-listing.js
  assets/js/admin-builder-archive.js
  assets/js/admin-custom-field.js
  assets/js/admin-import-export.js
  assets/js/admin-main.js
  assets/js/admin-plugins.js
  assets/js/admin-setup-wizard.js
  assets/js/all-authors.js
  assets/js/all-listings.js
  assets/js/all-location-category.js
  assets/js/author-profile.js
  assets/js/checkout.js
  assets/js/directorist-dashboard.js
  assets/js/directorist-plupload.js
  assets/js/global-geolocation.js
  assets/js/global-main.js
  assets/js/global-markerclusterer.js
  assets/js/google-map.js
  assets/js/openstreet-map.js
  assets/js/public-add-listing.js
  assets/js/public-atmodal.js
  assets/js/public-geolocation-widget.js
  assets/js/public-main.js
  assets/js/range-slider.js
  assets/js/search-form.js
  assets/js/single-listing-google-map-widget.js
  assets/js/single-listing-google-map.js
  assets/js/single-listing-openstreet-map-widget.js
  assets/js/single-listing-openstreet-map.js
  assets/js/single-listing.js
  assets/src/js/public/components/instantSearch.js
  package-lock.json
  yarn.lock
Labels: Type: Bug, Type: Improvement

#1557 fix conflict with pricing plan
  includes/classes/class-add-listing.php
Labels: Type: Bug
