Repository sovware/directorist, pull requests merged in 2025-09, with the labels that each got.

#2468 Fix: Relevant listings transition speed adjusted from 1s to 3s
  templates/single/section-related_listings.php
Labels: Priority: High

#2472 Fix: Carousel disappears after scrolling past 20 photos
  assets/css/admin-main.css
  assets/css/admin-main.min.css
  assets/css/admin-main.rtl.css
  assets/css/admin-main.rtl.min.css
  assets/css/all-listings.css
  assets/css/all-listings.min.css
  assets/css/all-listings.rtl.css
  assets/css/all-listings.rtl.min.css
  assets/css/public-main.css
  assets/css/public-main.min.css
  assets/css/public-main.rtl.css
  assets/css/public-main.rtl.min.css
  assets/js/listing-slider.js
  assets/js/listing-slider.min.js
  assets/src/js/global/map-scripts/add-listing/google-map.js
  assets/src/js/public/listing-slider.js
  assets/src/js/public/search-form.js
  assets/src/scss/component/_add-listing.scss
  assets/src/scss/component/_listing-slider.scss
  languages/directorist.pot
Labels: Priority: High

#2485 Improve: Improve the highlight for the select input list
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/all-listings.css
  assets/css/all-listings.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/src/scss/base/_general.scss
Labels: Priority: High

#2482 Fix: Listing Slider and Carousel Settings overlay Issue
  assets/css/admin-main.css
  assets/css/admin-main.min.css
  assets/css/admin-main.rtl.css
  assets/css/admin-main.rtl.min.css
  assets/css/all-listings.css
  assets/css/all-listings.min.css
  assets/css/all-listings.rtl.css
  assets/css/all-listings.rtl.min.css
  assets/css/public-main.css
  assets/css/public-main.min.css
  assets/css/public-main.rtl.css
  assets/css/public-main.rtl.min.css
  assets/src/js/global/map-scripts/add-listing/google-map.js
  assets/src/js/public/components/category-custom-fields.js
  assets/src/js/public/search-form.js
  assets/src/scss/layout/admin/builder/_builder_style.scss
  languages/directorist.pot
Labels: Priority: High

#2509 Fix default pricing type issue
  includes/class-helper.php
  templates/listing-form/fields/pricing.php
Labels: Type: Bug

#2517 Fix: Keep Add Listing Accordion Always Open
  assets/css/admin-main.css
  assets/css/admin-main.rtl.css
  assets/css/all-listings.css
  assets/css/all-listings.rtl.css
  assets/css/public-main.css
  assets/css/public-main.rtl.css
  assets/js/add-listing.js
  assets/src/js/global/add-listing.js
  assets/src/scss/component/_add-listing.scss
Labels: Priority: Medium
